### ISSUE TITLE
Brainstorm Bounceback Reduction for Home Page

### ISSUE THREAD

**Issue by amycoffin** [BRCAChallenge/brca-exchange#1033]
- one option is good examples of variant details
- most common search term is BRCA1 
- we need a 'next click' page that is a hook; picture should be there

**Comment by zfisch** [comment]
Added @melissacline to this issue.

Some background: On the 4/9/19 dev call we discussed ways to encourage users to interact further with the site. One of the primary suggestions was to include some links to variants of particular interest just below the search bar. We'll also have improved analytics following the next production release which should help us better understand bounce rates -- we don't currently track navigation well since we're using a (mostly) single page app.
