### ISSUE TITLE
URL redirection

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#1049]
- [x] URL redirect to latest version of a variant by default with notice and link to old version
- [x] Update wording around data from other (future) versions of a variant
- [x] Allow parameter use to suppress redirection message
- [x] Notify user if there's a newer version of a variant and provide a link

Also worth reviewing what data is displayed when viewing older versions of a variant.

wireframe: https://docs.google.com/presentation/d/1CpqoXilGvnhu2Y2pLo4LkktGlStqROCpjWg13p1uM-A/edit#slide=id.g59d0256d17_0_0

**Comment by falquaddoomi** [comment]
I've submitted a first pass at this in PR #1052. The verbiage and appearance of the notices might need to be tweaked a bit, but otherwise it's working.

I was surprised to discover that the site currently displays the newest data for the variant regardless of what version is actually requested. I've changed that behavior to instead look up the data corresponding to the ID the user specified.
