### ISSUE TITLE
Beta Fix: Summary to Detail View Pop-Up problem

### ISSUE THREAD

**Issue by amycoffin** [BRCAChallenge/brca-exchange#1058]
When on a variant details page, I clicked from detail view --> summary view --> detail view. When doing so, the normal pop up came up. Upon clicking "Yes," the pop up doesn't go away. It sort of exhibits behavior as if it will go away (floats up quickly), but remains as I try and navigate the page.  The "No" button doesn't make it go away either. When I refresh, I am in detail view. 

This behavior is not observed on production.

**Comment by melissacline** [comment]
Good catch, @amycoffin !

I'm seeing the same thing on beta, and here's the information I can add.
1. On the home page, I can toggle between detail view and summary view and back to detail view by clicking on the blue summary/detail view box, with the expected behavior.
2. On the variants page, I can do the same.  By clicking on the detail/summary view box, or by clicking on "Show Summary Data Only" and then "Show Detail View", I can move between summary and detail view with the expected behavior.
3. **Only on the Variant Details page,** the toggle seems to be getting stuck.  I can click on the Detail View box to switch to Summary View, successfully.  Then when I click on the Summary View box to switch to Detail View, the pop-up window appears, and doesn't go away when I click on it.  See the attached screen shot.
@zfisch Care to do the honors?  Thanks!
<img width="1115" alt="Screen Shot 2019-05-26 at 3 11 34 PM" src="https://user-images.githubusercontent.com/1714823/58387765-307a8280-7fc9-11e9-8666-8c85cb1304bb.png">
