### ISSUE TITLE
Ensure that all populated tiles expand upon landing on or refreshing a variant details page

### ISSUE THREAD

**Issue by amycoffin** [BRCAChallenge/brca-exchange#1059]
This is not a barrier to May release. 

However, if you collapse tiles on one Variant Details Page, they stay collapsed as you continue to navigate other variants. This can hide data from users. Ideally, any time you land on a new variant details page, or even refresh a page, all data should be displayed regardless of previous user behaviors.

**Comment by melissacline** [comment]
That's debatable.  Certain users might want to keep certain tiles collapsed indefinitely, in which case we'd be doing them a disservice by expanding them with each new variant.  As long as the tile doesn't disappear from view completely, we're arguably fine.

**Comment by zfisch** [comment]
I also understood that storing collapsed vs expanded tiles in local storage is intentional -- i.e. if a user collapses a tile, it stays collapsed regardless of refresh until they expand it again or clear their browser cache.

@amycoffin @melissacline Can we mark this issue as closed or does it need further discussion?

**Comment by amycoffin** [comment]
@zfisch yeah let's go ahead and close it, as long as it's been discussed and it's intentional
