### ISSUE TITLE
update LOVD submission definition and resume downloading dynamic data

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#1115]
functional analysis fields are no longer provided

**Comment by amycoffin** [comment]
Here are the LOVD wireframes: 
https://docs.google.com/presentation/d/1IBp9zaHihtX0pJEYHabxysEP4xfq9BaGaSbOMI_LeZc/edit#slide=id.p

**Comment by zfisch** [comment]
@amycoffin @melissacline 

I understand we want to add the following fields to the UI: "remarks", "classification", and "frequency". What names do we want to display them as? (e.g. Variant Remarks, Clinical Classsification, Variant Frequency).

Also, do we intend to continue showing Variant Effect or would you like me to remove that field? If removed, should I remove it from everywhere (data and history included) or just the UI?

**Comment by amycoffin** [comment]
@melissacline should confirm, but my understanding is that:

A) Variant Effect is indeed useful, but it will no longer be highlighted in the header bar (blue bar), and will be replaced by Clinical Classification in the header bar 
B) Variant Frequency can be displayed as "Individuals", per the old decisions on the old LOVD data, and as it is reflected in the wireframes. (this makes sense to me, because it is more related to cohort stuff rather than an official frequency. If labeled "frequency," one would ask the question "compared to what?" Since these are individual studies, and "individuals" is a less specific term, it makes a little more sense in this context). 
C) Remarks can be displayed as variant remarks

**Comment by amycoffin** [comment]
Actually, @melissacline, I'm not sure whether my logic about the "Individuals" label makes sense, because currently these are displayed as integers (i.e. literal individuals), and the new data is in a fraction format. Can you make a final call on what that field should be called?

**Comment by zfisch** [comment]
It will also be confusing if we have both fields in the data download -- i.e. what's labeled as "individuals" in the ui refers to "frequency" in the data, and the "individuals" field in the data isn't anywhere in the ui

**Comment by melissacline** [comment]
B. Let's label frequency as frequency, as it appears on LOVD.  @amycoffin, I appreciate what you're getting at with "individuals", but the term is so nonspecific that I'd be confused about what it:s getting at.

A. The EGG decision was to not show the functional impact field on the screen - too confusing - but it's okay if it's in the download file.

**Comment by zfisch** [comment]
@melissacline by "functional impact" do you mean to not display variant effect?

**Comment by melissacline** [comment]
Yes, that's what I mean.  It's the field that we label as variant effect, that has the cryptic symbolic encoding of submiter / curator interpretations.

**Comment by zfisch** [comment]
+/+
😬
