### ISSUE TITLE
Attempting to re-run pipeline using `make run-pipeline` fails

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#1124]
to recreate:

run generate_release.sh using commit 96e9c274 (on gnomadIntronic branch)
after pipeline failure, cd into code/pipeline directory of release and run `make run-pipeline`

error is as follows:

> WARNING: BRCA Code base mounted from host file system
Running brca exchange pipeline:
Git hash: commit 96e9c2746ef5816b41f55c40d0665e7562c7beca
Attempting to run task GenerateReleaseArchive
2019-10-08 00:27:59,142 setup_logging.py logging configured via *.conf file
Pid(s) set([12]) already running

Not sure why this started happening now...

**Comment by zfisch** [comment]
@izcram could you take a look at this before tomorrow's dev call? hoping we can figure it out quickly since it hinders pipeline dev

**Comment by izcram** [comment]
As discussed, probably an issue with locks, perhaps you could try with '--no-lock'. But this may not be it, since locks should be in `/tmp/luigi` (https://luigi.readthedocs.io/en/stable/api/luigi.interface.html#luigi.interface.core.lock_pid_dir). But `/tmp` is part of a container so it is recreated at every new run.

**Comment by zfisch** [comment]
Sure enough, running with `--no-lock` gets things running again... will investigate a little further and determine if a fix is required or if running with `--no-lock` is an appropriate solution temporarily or permanently
