### ISSUE TITLE
ENIGMA variant coming back with incorrect coordinates

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#1126]
What causes the variant to come back with incorrect coordinates in the latest release? Is this causing any other unwanted changes to the data? 

The variant is valid and does appear in a previous release: https://brcaexchange.org/variant/229801

BRCA1    chr17:None:None>None    NM_007294.3    c.3714_3747delTTCTCAGTCTACTAGGCATAGCACCGTTGCTACC    3829insTdel35    Q1240Vfs*13    -    OMIM    BREAST-OVARIAN CANCER, FAMILIAL, SUSCEPTIBILITY TO, 1; BROVCA1 (604370)    Disease    Pathogenic    9/8/16    ENIGMA BRCA1/2 Classification Criteria (2015)    https://submit.ncbi.nlm.nih.gov/ft/byid/hxnfuuxx/enigma_rules_2015-03-26.pdf        Variant allele predicted to encode a truncated non-functional protein.    Curation    Germline    SCV000300003.2    p.(Gln1240ValfsTer13)    7008

**Comment by izcram** [comment]
In a new version of the ClinVar XML dump the `referenceAlleleVCF` and `alternateAlleleVCF` got dropped for this variant, which we need to calculate our variant representation:
```
<SequenceLocation Assembly="GRCh38" AssemblyAccessionVersion="GCF_000001405.38" AssemblyStatus="current" Chr="17" Accession="NC_000017.11" start="43091784" stop="43091817" display_start="43091784" display_stop="43091817" variantLength="34"></SequenceLocation>
```
instead of previously:
```
<SequenceLocation Accession="NC_000017.11" Assembly="GRCh38" AssemblyAccessionVersion="GCF_000001405.38" AssemblyStatus="current" Chr="17" alternateAlleleVCF="C" display_start="43091784" display_stop="43091817" positionVCF="43091783" referenceAlleleVCF="CGGTAGCAACGGTGCTATGCCTAGTAGACTGAGAA" start="43091784" stop="43091817" variantLength="34"></SequenceLocation>
```

 We can calculate this ourselves quite easily using the infrastructure here: 
https://github.com/BRCAChallenge/brca-exchange/blob/31c60e5c33251a0b77f2bcd1b45bad50d54d61b8/pipeline/common/variant_utils.py

However, since we handle deletion and insertions (e.g. CG>C instead of "G>None") as indels this code would need to be extended a bit by fetching the base just before the deletion to go from "G>None" to CG>C .

Computing the ref and alt ourselves would also allow us to include >300 structural variants from ClinVar which have currently been ignored.
