### ISSUE TITLE
Off-by-one error in variant position

### ISSUE THREAD

**Issue by melissacline** [BRCAChallenge/brca-exchange#272]
Reported by Ricardo.X.Gutierrez@questdiagnostics.com
On Thu, Dec 1, 2016 at 11:37 AM, Gutierrez, Ricardo X <Ricardo.X.Gutierrez@questdiagnostics.com> wrote:
Good Morning,
 
In reviewing the information posted at http://brcaexchange.org/variant/13517, I noticed that in the Synonyms field, the nucleotide numbering appears incorrect “U43746.1:c.2304T>C,” and should be U43746.1:2305T>C.” Please correct me if I am wrong. I am not sure if this applies to other records in your database.
 
Have a good day,
 
Ricardo Gutierrez Jr. M.S.
Scientist, Molecular Genetics
Quest Diagnostics | Action from Insight | 33608 Ortega Highway | San Juan Capistrano, CA 92690 USA | phone 949.728.4564 | fax 949.728.4874 | Ricardo.X.Gutierrez@QuestDiagnostics.com | QuestDiagnostics.com

**Comment by melissacline** [comment]
Charlie, could you do a sanity check on this issue?  U43746.1:c.2304T>C is listed as a synonym of NM_000059.3:c.2077T>C, which is in ClinVar at https://www.ncbi.nlm.nih.gov/clinvar/variation/236834/.  I'm not sure where we compute U43746.1:c.2304T>C as a synonym of this variant, but it sounds like we could use a sanity check on the variant numbering.  Thanks!

**Comment by cmarkello** [comment]
@melissacline I'm having trouble seeing how those are synonymous. They both lie in the same exon 11 of BRCA2, but are in clearly two different locations of that exon with different neighboring sequences. "U43746.1" looks like an old reference sequence accession ID. It's possible "U43746.1:c.2304T>C" came from the synonym generation script, I'll take a look.

**Comment by cmarkello** [comment]
@melissacline So I'm not sure, but I think I found a potential bug in the `brca_pseudonym_generator.py` script here: https://github.com/BRCAChallenge/brca-exchange/blob/master/pipeline/data_merging/brca_pseudonym_generator.py#L151-L154

After now understanding how some ClinVar variants can have empty REF strings prior to variant normalization, the edge-case handling there may be incorrect since the script doesn't attempt to normalize the variant prior to feeding it into the pyhgvs library. Though according to the councyl pyhgvs documentation (https://github.com/counsyl/hgvs), they seem to imply that their program does do this conversion. It's hard for me to tell.

Ultimately the refseq transcript "U43746.1" may just be too out of date. The genbank page says it's from 1996 (https://www.ncbi.nlm.nih.gov/nuccore/U43746). So really, I guess "U43746.1" should be left out of the BRCA2 alternative transcripts that `brca_pseudonym_generator` uses to generate these synonymous variants. (https://github.com/BRCAChallenge/brca-exchange/blob/master/pipeline/data_merging/brca_pseudonym_generator.py#L135)

**Comment by melissacline** [comment]
@cmarkello where does this stand?  Is this part of the fix that you made as part of last month's release, or is it a separate issue?  Thanks!
