### ISSUE TITLE
Increase height of Community Pages map

### ISSUE THREAD

**Issue by melissacline** [BRCAChallenge/brca-exchange#509]
Keep the current width of the map under Community Pages, but increase the height so that each continent is shown only once.

**Comment by falquaddoomi** [comment]
I attempted to increase the map height to fix the duplicate continent/marker issue, but it appears to only increase the amount of map you can see; it doesn't affect the zoom. (I did end up increasing the map size to 450px because it does look better.)

I was able to find a zoom level (2 instead of 1) that *just* fits all the markers, although both the member in Hawaii and New Zealand are right against the edge of the map. I moved the zoom control from the bottom right to the bottom left (it's in an empty spot in the ocean now) so as not to occlude New Zealand.

In order accommodate all the markers horizontally at the new zoom level, I increased the number of columns for the page at the "medium" bootstrap size class from 8 to 10. I also took the liberty of changing the "small" class columns from 10 to 12, as the page looked a bit squashed at that size class.

**Comment by falquaddoomi** [comment]
Fixed by 99d3e3441d31223ea56b68eb8b52a03247b8b0e5 (and indirectly ae427da3a98ce2a52de5285814557d3a42b99733.)
