### ISSUE TITLE
Mislabeled Data Portals (Blue Icon) 

### ISSUE THREAD

**Issue by amycoffin** [BRCAChallenge/brca-exchange#654]
1. Open an incognito Chrome Window 
2. Open two tabs and go to brcaexchange.cloudapp.net in both tabs
3. Search BRCA1 or BRCA2 in one tab and select a random variant from the search results to arrive on the Variant Details Page
4. In the same tab, switch from the data portal that you entered by default to the other side using the button provided at the bottom of the page. (It does not matter if you are going from All Public —> Expert or Expert —> All Public) 
5. In the second tab, search BRCA1 or BRCA 2 and select a random variant from the search results 
6. Note that you will be provided the view that you switched to in the other tab, but the blue icon at the top of the page will mislabel the data portal that you are in. The blue icon will still read what it did when you first navigated to the BRCA Exchange site. 
7. The button to switch data-views will remain accurate and in tact.
8. The icon only mislabels the data portal in the second tab; the first tab's buttons and icons remain accurate and intact. 
<img width="1367" alt="screen shot 2017-11-11 at 10 34 48 pm" src="https://user-images.githubusercontent.com/25374391/32754013-06339410-c884-11e7-9431-1dc43004f048.png">
<img width="1259" alt="screen shot 2017-11-11 at 10 35 48 pm" src="https://user-images.githubusercontent.com/25374391/32754014-0653edfa-c884-11e7-9a5b-e4760b5592a4.png">

**Comment by zfisch** [comment]
Nice find @amycoffin!

This is an interesting issue that stems from our use of localstorage. What's happening is when a user changes modes on one tab, it updates localstorage to reflect the change. The change to localstorage persists to other tabs, but we don't currently update the view based on real time changes to localstorage (mode is initiated when the webpage first loads, but currently doesn't update when changing views, e.g. from search to table to details).

We have a few options, but here are the ones that make most sense to me:

1. When a user changes modes in one tab, that change is reflected in other tabs when a user changes views (e.g. from table to detail, or search to table, etc.).

2. When a user changes modes in one tab, that change is NOT reflected in other tabs at all (this is substantially trickier since we have to intelligently override localstorage somehow).

FWIW, we use localstorage to allow users to persist their viewing preferences when leaving and revisiting the site, as well as handling URL specific views.

@melissacline @amycoffin how would you like me to proceed or would you like to schedule a time so I can screenshare this with you so it makes more sense?

**Comment by zfisch** [comment]
@melissacline checking in on this issue

**Comment by melissacline** [comment]
Thanks for checking!  The option that makes the most sense to me is 1, that when a user makes a change in one tab, that change is reflected in other tabs.  I'm grateful that it's the easier one.

**Comment by melissacline** [comment]
Just verified as follows:
- opened a tab to brcaexchange.cloudapp.net.  Searched for a random variant (p.(Leu358CysfsTer16)) in Expert-Reviewed mode.
- opened another tab to brcaexchange.cloudapp.net.  Went into All Public Data mode.  Searched for the same variant.
- Went back to the first tab and reloaded the page.  Voila, it's in All Public Data mode.
