### ISSUE TITLE
get remaining fields from clinvar for report tiles

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#691]
star rating, date?, any others?

**Comment by zfisch** [comment]
turns out the star rating is determined by the review status, which we already collect. we also already have the date.

@melissacline are there any other fields that we don't already collect that people want?

**Comment by melissacline** [comment]
Yes, people want more of the aliases in ClinVar.  For example, for the BRCA2 variant c.-196G>A, our list of synonyms are U43746.1:c.32G>A.  In ClinVar (see https://www.ncbi.nlm.nih.gov/clinvar/variation/434530/), the HGVS synonyms for this variant are:

NG_012772.3:g.5032G>A
NM_000059.3:c.-196G>A
NC_000013.11:g.32315511G>A (GRCh38)
LRG_293t1:c.-196G>A
NC_000013.10:g.32889648G>A (GRCh37)
LRG_293:g.5032G>A

It turns out that the genomic counselors want a big list of synoyms, because people bring in old genetic test reports from relatives (with unpredictable variant nomenclature).  Note that the (GRCh38) and (GRCh37) above are optional, those are actually indicated by the accession sequence and are for display only.

**Comment by zfisch** [comment]
@izcram this ticket could probably be resolved when refactoring the enigma pipeline since it's just additional fields from the clinvar xml source file

**Comment by zfisch** [comment]
@izcram checking to see if this issue was addressed in the latest changes or where it currently stands

**Comment by izcram** [comment]
@zfisch, @melissacline  Yes, some progress recently. We need to think a bit more about requirements.

It seems, we could extract 'synonymous' variant designations from `(Reference)ClinVarAssertion/MeasureSet/Measure/AttributeSet/Attribute` elements in the clinvar XML. Nicely enough, there is an exhaustive list of 'Type's which can appear (doesn't mean they all appear): https://github.com/ncbi/clinvar/blob/master/xsd/clinvar_public.xsd#L428

Now, the question is what we extract and where we put it. Shall we take them all and add them all into the already existing `Synonyms` column or should we do some finer treatment? What should we show on the UI? There might be perhaps up to 50 or so designations for a single variant.
Also, note, that there are designations at both nucleotide and protein level and I'm not sure whether we should throw them into the same bucket (we can do this, if the 'bucket' is for display/search purposes exclusively)

**Comment by melissacline** [comment]
Let's try adding a new Synonyms field to the Variant Nomenclature tile,
with all of the synonyms (protein, nucleotide and all).  If it gets
painfully long, we can experiment with adding a scrollbar.  Joe's been
looking into that for the literature search display, and has been working
through the nuances of the scrollbars on macs.

**Comment by zfisch** [comment]
@melissacline do we know that people will want to search on these? If so, we should include them with the existing synonyms, if not, we should create a new column (maybe "Synonyms_ClinVar") and we can include/exclude them as needed without unnecessarily slowing the existing search algorithm.
