### ISSUE TITLE
Widen the variant search box so that the default search string is not truncated

### ISSUE THREAD

**Issue by melissacline** [BRCAChallenge/brca-exchange#81]

**Comment by falquaddoomi** [comment]
Does this issue apply just to the landing page, or also to the variant search page that displays the results table? I assume both; I'm still working on expanding the horizontal space for the search box without causing the page selector to wrap.

Also, I'm not sure if this is the same or a different issue, but mobile screen widths (e.g. <430px) still truncate the placeholder text -- despite the search box being full-width -- due to the size of the font and/or the length of the placeholder text. In order to fix this, we could use a CSS media query to reduce the font size (although it's debatable if this is desirable), or we could shorten the placeholder text itself, but this would have to be done via a JS resize handler since placeholder text isn't customizable via CSS.

**Comment by maryjgoldman** [comment]
Relevant connected issues:
https://github.com/BD2KGenomics/brca-website/issues/143
https://github.com/BD2KGenomics/brca-website/issues/142
https://github.com/BD2KGenomics/brca-website/issues/141

**Comment by maryjgoldman** [comment]
Also connected to my comment on #86

**Comment by melissacline** [comment]
If we can detect that people are running on mobile devices, we can redirect them to the mobile app.
