### ISSUE TITLE
Handle Special Case #3: De Novo Donor is better than the wildtype donor because of the donor splice site damage

### ISSUE THREAD

**Issue by amycoffin** [BRCAChallenge/brca-exchange#822]
Where? Splice-level Estimation/ De Novo Donor tab

**Indication per data:**
deNovoZscore > closestDonoraltZ

**Text implemented on HCI:**
This variant was promoted one category because the Z score for the de novo splice site introduced by the mutant is higher than the z score of the alternative donor sequence of this exon. 

**Suggested text for BRCA Exchange:**
This variant was promoted one category because the Z score for the de novo splice site introduced by the variant is higher than the z score of the altered wild type donor sequence of this exon.

**Comment by falquaddoomi** [comment]
Originally implemented in commit 03dc1bf2bf7bd9824233823db10e3d6e0dd2a2df. The text was copied from slide 15, which reads "This variant was promoted one category because the Z score for the mutant is higher than the z score of the alternative donor sequence of this exon."

I'm surprised that that doesn't match either of the given descriptions, but I'll change it to the suggested BRCA Exchange text.

**Comment by amycoffin** [comment]
It doesn't match because I accidentally edited as I was copying, but we need to flag suggested new text as important for review by EGG/Sean.

**Comment by amycoffin** [comment]
@falquaddoomi is this issue also resolved?

**Comment by falquaddoomi** [comment]
Yes, this is resolved; I'll go ahead and close it.
