### ISSUE TITLE
Update getVarConsequences() methods to better reflect varConsequences

### ISSUE THREAD

**Issue by amycoffin** [BRCAChallenge/brca-exchange#831]
**Current Functionality:**

getVarConsequences (line 247) currently calls Ensembl VEP to retrieve characteristics of a variant that are relevant to pathogenicity, also called "consequences." VEP returns a dictionary with the following structure, with bolded keys/values returned by current getVarConsequences().  

{'allele_string',..., **'transcript_consequences':** [{'amino acids': [], ..., **'consequence_terms': ['missense_variant,** splice_region_variant]}]}

Lines 274-281 indicate that only the first item in the consequence terms array is returned:
` return gene["consequence_terms"][0] `(line 281).

Referring to the above example, the current code dictates that 'missense_variant' is all that is returned by getVarConsequences, and we omit useful information, such as  'splice_region_variant' . 

**Action to Take**:
**Update getVarConsequences to return the entire consequence_terms array. Append this array to the end of the priors output as its own column, calling the column varConsequences**

getVarConsequences is used in conditionals to populate output data based on variant consequence terms (lines 1401, 1719, 2216, 2404, 2699, and 3174). Conditionals will need to be altered to address arrays rather than strings, but this will be handled in issue #832 .   

All possible consequence terms can be found [here](https://uswest.ensembl.org/info/genome/variation/prediction/predicted_data.html#consequence_type_table).

**Comment by amycoffin** [comment]
@rcurrie I am assigning you to these issues for now, because you where there  but if you don't feel comfortable implementing them, feel free to just unassign yourself and we can figure out whether Melissa or Zack will. This loop will close somewhat easily.

**Comment by rcurrie** [comment]
After talking with @amycoffin and indirectly @melissacline here's the plan:

- [ ] Modify getVarConsequences() to return a list
- [ ] Change all comparisons of the result to 'if in'
- [ ] Run the test 88 variants and see if the output is the same

Amy is going to look at the if's to see if they really are all mutually exclusive as well as the default else to see if it makes sense given there are 20+ consequences it implicitly resolves to.

**Comment by rcurrie** [comment]
@melissacline @amycoffin Good news - Chloe's test 88 variants generated identical priors output! I'm going to do a bit more testing to see if any of the dangling else clauses are being taken or not - they may never occur. Will also see about stepping up to the full input just to see if it changes or not.

**Comment by rcurrie** [comment]
@amycoffin There appears to be where the result of getVarConsequences() is examined for a certain value and if it doesn't contain it another branch is taken implying that all other results are valid (aka default else):

[**A**](https://github.com/rcurrie/brca-exchange/blob/getVarConsequences-return-list-832/pipeline/splicing/calcVarPriors.py#L2696):
```
if "stop_gained" in varCons:
else
```

[**B**](https://github.com/rcurrie/brca-exchange/blob/getVarConsequences-return-list-832/pipeline/splicing/calcVarPriors.py#L3171)
```
if "3_prime_UTR_variant" in varCons:
elif "5_prime_UTR_variant" in varCons:
else:
```
I've verified they are reached using the [88 test variants](https://github.com/rcurrie/brca-exchange/blob/getVarConsequences-return-list-832/pipeline/splicing/tests/variants_long.tsv)

If you can read through those two places and reason whether the default else is reasonable for all other values of consequences from the [ensembl vep list](https://uswest.ensembl.org/info/genome/variation/prediction/predicted_data.html#consequence_type_table) we can increase our confidence that returning the list is correct.

@melissacline I have the built.tsv from the latest release. Another validation would be for me to run the pipeline with chloe's original logic (ie [0]) and the new logic and see if there is any difference over all variants (24k). I'm still concerned about finding logic like this in the code - looking a bit more there are other places where, for example, a function returns a value sometimes and other's nothing. I'm adding assertions to those to make sure they are never taken.

**Comment by melissacline** [comment]
@rcurrie thank you, thank you, thank you!

**Comment by izcram** [comment]
@rcurrie Not much idea myself. But given that pyhgvs_cDNA is always available it makes sense to use this. See also https://github.com/BRCAChallenge/brca-exchange/blob/master/pipeline/data_merging/brca_pseudonym_generator.py#L165 and https://github.com/BRCAChallenge/brca-exchange/blob/master/pipeline/data_merging/brca_pseudonym_generator.py#L256 to see where it comes from. I suspect, the HGVS_cDNA field was used for simplicity.

**Comment by melissacline** [comment]
I can add some history here.  HGVS_cDNA is one of the input fields that's used to compute pyhgvs_cDNA.  They seem redundant, and there's a reason for that.  Zack wanted to create a new field (pyhgvs_cDNA) rather than update the old field (HGVS_cDNA), for the purpose of traceability.  So, pyhgvs_cDNA is the better one to use.

**Comment by rcurrie** [comment]
@melissacline @amycoffin @zfisch 

I've run the latest splicing pipeline across [all variants](https://github.com/rcurrie/brca-exchange/blob/getVarConsequences-return-list-832/pipeline/splicing/tests/variants_all.tsv) and added the [calculated priors](https://github.com/rcurrie/brca-exchange/blob/getVarConsequences-return-list-832/pipeline/splicing/tests/priors_all.tsv) to my fork as a test case. In the same folder are the smaller sets that chloe used as validation. This version of the pipeline carries the list returned from VEP all the way through, changing == to in. Its output is identical to the prior version that just looked at VEP[0] for the 88 test cases chloe provided. I tried to run all variants through the prior pipeline as well to see if it was identical but it crashed. Chatting briefly with Melissa it sounds like we the focus should be on validating current output. I have not adjusted the code yet to include the full vep list in the output as that needs to be coordinated with the downstream users.

**Comment by amycoffin** [comment]
@rcurrie is it possible just to make a new, isolated function that returns the list it as it's own column, allowing us to use the full list in implementation even if it doesn't get used in the calculations? It seems helpful to have that information for the validation process as well.

**Comment by rcurrie** [comment]
@amycoffin should be relatively easy, let me poke around the fields and propose something (at the moment I"m locked out of my dev server/courtyard as someone is being bad with the disk...)

**Comment by zfisch** [comment]
@rcurrie i ran some tests across several thousand variants today and found that consequence_terms were returned in order of severity as listed at https://uswest.ensembl.org/info/genome/variation/prediction/predicted_data.html#consequence_type_table. I don't think this sort order is necessarily reliable, but I do think it may have informed Chloe's logic in writing if/elif/else statements with regard to getVarConsequences.

Hopefully this is helpful in understanding the sometimes vague nature of the if statements, and maybe it informs a more readable method of writing them using `in` instead of `==`.

**Comment by rcurrie** [comment]
Looks like the errors I have been seeing when running all variants are due to the UCSC server rate limiter - which we hit quite easily with multiple threads. But we really should be just handing this locally as we have hg38.fa downloaded anyways so going to go ahead and do the work to get rid of that external request as it will fix this as well as speed things up quite a bit. Then I should be able to run all variants and exhaust a file with a list of VEP consequences as a new column.

**Comment by rcurrie** [comment]
Switched to calculating sequences directly instead of calling UCSC API. Oddly there was already a FASTA file loaded and specified in command line options but it was never being used anywhere in the code.

**Comment by rcurrie** [comment]
@amycoffin @melissacline @zfisch 

I've run built_with_mupit.tsv from the [latest release](http://brcaexchange.westus2.cloudapp.azure.com/backend/downloads/releases/current_release.tar.gz) and added its output to the repo as [built_with_priors.tsv](https://github.com/rcurrie/brca-exchange/blob/1337c86d5958cf98e36f0cc4166cb23d3ef6f8f5/pipeline/splicing/tests/built_with_priors.tsv). There is a new column now, varConsequences, with the list returned from VEP as a comma separated list. The errors I were encountering before were due to rate limits from the UCSC server. After a bit of spelunking I discovered that in fact the reference hg38.fa was never actually used - genome is passed all around but its never accessed. I've done a bit of reworking and it now gets the sequence completely locally and as a result 20645 variants run on 16 cores in 181 minutes. I've verified that Chloe's 88 test variants compute exactly as they did before (net of the new column). Still have some cleanup here and there but let me know if this gets you going for validation and/or if there is any other output required.

**Comment by zfisch** [comment]
@amycoffin `the variants.tsv file is used for its headers, to build the output file with existing headers + new headers` -- I'm not seeing this anywhere, could you show me where this happens? It's actually dangerous because this requires we update the file in the repo any time we make upstream changes to the pipeline. The input file has all the headers and data we need to generate an output.

**Comment by amycoffin** [comment]
inputData is the built.tsv file (see line 3449). My guess is that somehow the built.tsv file got renamed as variants.tsv, and now calcVarPriors takes it as a manual argument instead of letting the program default. @rcurrie , has the default on that argument been working for you?

csv.DictReader is used to make a DictReader instance out of inputData (variants.tsv), which allows each row to insert values to a set of fixed keys that are defined by the headers in variants.tsv. She uses these fixed keys to make fieldnames, hardcodes newHeaders, and then appends each to fieldnames in order to write outputData, which is a DictReader instance until it is written in line 3480. 

<img width="831" alt="screen shot 2018-08-06 at 1 20 59 pm" src="https://user-images.githubusercontent.com/25374391/43739169-efb73272-997b-11e8-864a-bd7b95d5cc50.png">

**Comment by rcurrie** [comment]
The files under tests/ are just for regression testing - not meant to be a version managed input or output for the website. The short and long ones in there are 8 and all 88 of Chloe's test files and I felt it was useful to also have a full set for testing/regression. The [command line defaults](https://github.com/rcurrie/brca-exchange/blob/getVarConsequences-return-list-832/pipeline/splicing/calcVarPriors.py#L3496) only specify the reference genome and refseq annotations files - the latter is built into the container as well. The headers are not external in headers.txt. BUT - there are tons of header field references throughout the code, and, for example, the genome reference was never used  although passed all throughout the code (the actual data was requested from the UCSC servers up until we hit rate limits this weekend and not it does use the genome reference but not passed in...). So, the long and short of it is the code and control flow is very elaborate and I'm trying to change as little as possible to get through validation at least priors computation logic wise.
