### ISSUE TITLE
update data deployment

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#960]
1. Need to be confident deployments will succeed and get a meaningful error if not.

2. Make sure deployments don't lock tables so users can still access (if they take > ~10 min)

3. Include simple commands to deploy locally, to dev, beta, and production. Really should be able to deploy to any machine but those should be automated.

4. Maintains existing functionality (deploys data, updates downloads directory with latest release, pushes to genome browser).

5. Explore options for coupling literature search and data deployment (currently separate scripts).

6. Can we get it to run in 5-15 minutes? Last deployment (12/6/18 data deployed to beta) took ~2 hours to complete after the first attempt crashed after ~8 hours.

**Comment by zfisch** [comment]
@falquaddoomi @izcram either of you particularly interested (and available) to work on this? No major rush, but worth putting on the radar. I can work on it if not.

**Comment by falquaddoomi** [comment]
Sure, I'd like to look into it.

**Comment by zfisch** [comment]
@falquaddoomi Awesome! Let me know if you need anything along the way or have any questions. The master script is at https://github.com/BRCAChallenge/brca-exchange/blob/master/deployment/deploy-data.

**Comment by falquaddoomi** [comment]
@zfisch Just to give a quick status update, I've been focusing almost completely on getting it to run quickly in a single transaction (which would prevent it from leaving the db in an intermediate state should it fail, at least). I've found that loading the variant/report diffs into a temporary table via `copy from`, then using an `insert-select` loop to associate them with their respective variants/reports is a lot faster than doing it in straight Python, at least on my local machine. I've made a few other minor cleanups and redundant code removals that make the code easier to work with, imho.

There are a few issues with the version of postgres that we're using (9.3) that'd be resolved by moving to a more contemporary version (e.g., 11). For instance, there appear to be some diffs that refer to the same variant/report, which violates the uniqueness constraint on the variant_id/report_id column in the diff table. Postgres 9.5 introduced the `on conflict do nothing` clause to `insert`, but we're unfortunately running 9.3. Also, indexing the `Genomic_Coordinate_hg38` column would improve performance quite a bit since we use it for looking up variants frequently, but since it can be quite long (more than 70,000 characters in some cases) it's too big for a regular btree index. Instead, we'd have to use a hash index, but hashes weren't great until they received attention in postgres 10.

**Comment by zfisch** [comment]
Nice! If we're able to upgrade postgres without too much trouble it certainly sounds like it would be helpful. Wanna give it a shot and see how it goes?

It's also ok to do a couple rounds of improvements if that's easier. For example everything before upgrading PG could be one PR and everything after could be another.
