### ISSUE TITLE
Fix Indentations on Variant Details Tiles

### ISSUE THREAD

**Issue by amycoffin** [BRCAChallenge/brca-exchange#971]
The Allele Frequency Reference sets tile indents are not aligned, or rather, right aligned:
<img width="517" alt="screen shot 2019-01-10 at 3 43 29 pm" src="https://user-images.githubusercontent.com/25374391/50996979-68d56480-14f1-11e9-8fc8-443c3ab610a8.png">
I personally think that subtile titles (blue rows) should be Left aligned, to sort of mirror the main titles, but maybe this is just a matter of opinions and doesn't matter much. Right alignment makes sense for normal data labels (white rows).

This one is less of an issue, but I did notice that the LOVD tile's indentations seem unnecessarily far from the margin:
<img width="507" alt="screen shot 2019-01-10 at 4 05 18 pm" src="https://user-images.githubusercontent.com/25374391/50997062-9b7f5d00-14f1-11e9-96fc-f331ec0edb04.png">

Can we align the Allele Frequency tile labels, and perhaps move over the LOVD labels a bit?

**Comment by falquaddoomi** [comment]
Sure, that's doable; I should note that it'll introduce special cases for different variants of the collapsible tiles (they currently all share the same code). They're currently all styled that way because they're label-value pairs -- you'll notice that they have the same alignment as the label-value pairs inside the other tiles.

Still, I think it's worth it to give the LOVD titles a bit more breathing room and to make the allele frequency titles look  less weird.
