### ISSUE TITLE
QA Beta

### ISSUE THREAD

**Issue by amycoffin** [BRCAChallenge/brca-exchange#985]
- [x] links/functionality on variant details page

- [x] hover overs/question mark links on variant details page

- [x] links/functionality throughout Help/FAQ

- [x] variants table functionality

- [x] Links & Functionality throughout More pages

- [x] Summary View check-up

**Comment by amycoffin** [comment]
@zfisch @melissacline 
Download button is broken, downloads empty tsv file:
<img width="1165" alt="screen shot 2019-02-06 at 3 30 54 pm" src="https://user-images.githubusercontent.com/25374391/52371757-5c76f580-2a24-11e9-82e7-e3e489822272.png">

**Comment by zfisch** [comment]
@amycoffin thanks for finding this, looking into it

**Comment by zfisch** [comment]
Noticed the same issue with the download button on dev/beta/prod.

I spent a good deal of time trying to understand what's going on, but I'm currently stumped. The strangest part is that I'm able to get proper output from a dev server http://brcaexchange-dev.gi.ucsc.edu:9003 using the same code, database and machine (both are running the latest master and pointing to the storage.pg db on http://brcaexchange-dev.gi.ucsc.edu).

The most likely offending code are these lines in views.py:

```
query = "COPY ({}) TO '{}' WITH DELIMITER '\t' CSV HEADER".format(query.query, f.name)
# HACK to add quotes around search terms
query = re.sub(r'LIKE UPPER\((.+?)\)', r"LIKE UPPER('\1')", query)
cursor.execute(query)
```
 
For example, if I replace the query in /var/www/backend/beta/django/data/views.py with raw text as follows, clicking the download button generates a tsv file with the expected "test" content:

```
f.write('test')
f.seek(0)
```

@falquaddoomi if you have a chance, could you take a look to see if you can find whatever it is I'm missing? I'd like to get a fix in before going to production :)

**Comment by falquaddoomi** [comment]
@zfisch Sure thing, currently looking into it. My guess is that it's a filesystem permission issue; the postgres "COPY TO <filename>" command runs in the database server's process, so perhaps in production something is stopping postgres from getting write access to the temporary file that the Django server process created. That'd explain why your test works, since it's still the Django process that's writing to the temp file.

The simple fix is to avoid using "COPY to <filename>" -- there's a variant of the command, "COPY TO STDOUT" which sends the data back to the client (Django), which would then stream it to the user. (I'll submit a PR with the fix in a few minutes.) Still, I'd like to figure out why postgres can't write to the temporary, file since it should be world-writeable, which would require poking around a bit on production...

**Comment by amycoffin** [comment]
@falquaddoomi There is also one broken link to cancer.gov in the first entry of Summary View/Help/Outside Resources "National Cancer Institute"

**Comment by zfisch** [comment]
@amycoffin All of the latest code is now on beta. Please take a look and let us know if there are any further updates needed :)

W.R.T. postgres permissions, I merged Faisal's update to use STDOUT instead of the old tempfile method -- I'm still unsure why that became an issue only recently, but I'd like to refocus on other issues at the moment and prioritize getting everything in order for release.
